### ISSUE TITLE
chinese code may become error code

### ISSUE THREAD

**Issue by MintBlue** [codebling/WindowsShortcuts#6]
if the file name contain chinese,the realfilename may become like "�̷�����". I guess if the return of the method `getNullDelimitedString` should change from `return new String(bytes, off, len);` to `return new String(bytes, off, len, Charset.forName("GBK"))`

**Comment by codebling** [comment]
Thanks for the report. Is `GBK` the system charset in this case?

**Comment by codebling** [comment]
Have you tried [mslinks](https://github.com/DmitriiShamrikov/mslinks)?

**Comment by MintBlue** [comment]
> Have you tried [mslinks](https://github.com/DmitriiShamrikov/mslinks)?

My computer is win10,I have tried mslinks,and found a very strange problem.

If a file is on  the dektop(like C:\Users\XXX\Desktop\1.txt),when use resolveTarget of mslinks to get the real path of the file's shortcut ,the path will be 1.txt,not contain the C:\Users\XXX\Desktop

**Comment by codebling** [comment]
This could be a bug. I am not a maintainer of mslinks, but I believe it is probably a more stable and complete project than the code in this repo. Could you attach a link that is causing a problem?

**Comment by codebling** [comment]
Stale issue, closing

**Comment by SinAcid** [comment]
> > Have you tried [mslinks](https://github.com/DmitriiShamrikov/mslinks)?
> 
> My computer is win10,I have tried mslinks,and found a very strange problem.
> 
> If a file is on the dektop(like C:\Users\XXX\Desktop\1.txt),when use resolveTarget of mslinks to get the real path of the file's shortcut ,the path will be 1.txt,not contain the C:\Users\XXX\Desktop

read Type if 4bit is 7 then position+9byte and read Type again
