### ISSUE TITLE
Bad alternative recommendation

### ISSUE THREAD

**Issue by ctwist** [codebling/WindowsShortcuts#7]
Not really an issue; more a comment.

readme.md recommends a "similar repository" mslinks as maybe a better choice.

No, it is not a better choice. It cannot handle shortcuts in Windows 10 special folders (e.g. Documents, Pictures). Refer to issue #13 which was reported 3 years ago and is still not fixed.

I suggest that you should remove your recommendation of an inferior product.

**Comment by codebling** [comment]
Thanks for the feedback! I take it this code here *did* work for you, then?

I specifically recommended the other repo on the basis of the author's activity closing issues (21/24 closed vs basically 0/3 here). I didn't write this code and thus have not much ability (even less will) to debug and fix it. If it works for you, great! To those for whom it doesn't work, I recommend the other repo (unless you can suggest something else!!). 

I definitely hope that my recommendation didn't cause you to lose any time!

**Comment by ctwist** [comment]
Actually, I didn't try mslinks because of your recommendation. The StackOverflow thread pointed me in that direction. Yes I did waste some time, but hopefully I have forewarned other potential users about its shortcomings.
Your code works perfectly for me.

**Comment by codebling** [comment]
Glad it helped! I think I might leave the recommendation there, at least people will know about the other repo and have another option if this code doesn't work. Thanks for the info and for sharing your experience!
